spring.application.name=lanchonete-api

spring.datasource.url=jdbc:h2:mem:lanchonete_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

# H2 Console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
